services:
  auth-db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge