services:
  auth-service:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - auth-db
    environment:
      DB_NAME: auth_db
      DB_USER: auth
      DB_PASS: 123
      DB_HOST: auth-db
      DB_PORT: 5432
      NODE_ENV: "development"
      JWT_SECRET: "supersecret"
    networks:
      - auth_network

  auth-db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge